/**
 * OCR
 * <b>The OCR API 'ocr' performs Optical Character Resolution on input files.</b>    The flow is generally as follows:  1. First upload an image/file using the /ocr POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /ocr/{jobid} endpoint, with the Job and Settings JSON as request body. The ocr extraction will now start.  3. Check the job status from the /ocr/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the OCR result using the /ocr/{jobid}/result GET endpoint. This will return the OCR result only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.ocr.api;

import com.sphereon.sdk.ocr.handler.ApiException;
import com.sphereon.sdk.ocr.model.OCRJobResponse;
import com.sphereon.sdk.ocr.model.ErrorResponse;
import com.sphereon.sdk.ocr.model.OCRResultResponse;
import com.sphereon.sdk.ocr.model.OCRJob;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OcrApi
 */
public class OcrApiTest {

    private final OcrApi api = new OcrApi();

    
    /**
     * Delete a job manually
     *
     * Delete the OCR job and all related files
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteJobTest() throws ApiException {
        String jobid = null;
        // OCRJobResponse response = api.deleteJob(jobid);

        // TODO: test validations
    }
    
    /**
     * Job definition and state
     *
     * Get the OCR job definition and current state. Please not that you can differentiate based on http response status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobTest() throws ApiException {
        String jobid = null;
        // OCRJobResponse response = api.getJob(jobid);

        // TODO: test validations
    }
    
    /**
     * Get all jobs
     *
     * Get all OCR job definitions and their current state.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobsTest() throws ApiException {
        List<String> status = null;
        // OCRJobResponse response = api.getJobs(status);

        // TODO: test validations
    }
    
    /**
     * Get the current ocr result
     *
     * Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResultTest() throws ApiException {
        String jobid = null;
        // OCRResultResponse response = api.getResult(jobid);

        // TODO: test validations
    }
    
    /**
     * Submit OCR job for processing
     *
     * Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitJobTest() throws ApiException {
        String jobid = null;
        OCRJob job = null;
        // OCRJobResponse response = api.submitJob(jobid, job);

        // TODO: test validations
    }
    
    /**
     * Upload first file
     *
     * Upload the first image file.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadFileTest() throws ApiException {
        File stream = null;
        // OCRJobResponse response = api.uploadFile(stream);

        // TODO: test validations
    }
    
}
