/* 
 * OCR
 *
 * <b>The OCR API 'ocr' performs Optical Character Resolution on input files.</b>    The flow is generally as follows:  1. First upload an image/file using the /ocr POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /ocr/{jobid} endpoint, with the Job and Settings JSON as request body. The ocr extraction will now start.  3. Check the job status from the /ocr/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the OCR result using the /ocr/{jobid}/result GET endpoint. This will return the OCR result only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Ocr.Model
{
    /// <summary>
    /// region
    /// </summary>
    [DataContract]
    public partial class Region :  IEquatable<Region>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Region" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Region() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Region" /> class.
        /// </summary>
        /// <param name="BottomLeft">BottomLeft (required).</param>
        /// <param name="BottomRight">BottomRight (required).</param>
        /// <param name="Center">Center (required).</param>
        /// <param name="TopLeft">TopLeft (required).</param>
        /// <param name="TopRight">TopRight (required).</param>
        public Region(Anchor BottomLeft = null, Anchor BottomRight = null, Anchor Center = null, Anchor TopLeft = null, Anchor TopRight = null)
        {
            // to ensure "BottomLeft" is required (not null)
            if (BottomLeft == null)
            {
                throw new InvalidDataException("BottomLeft is a required property for Region and cannot be null");
            }
            else
            {
                this.BottomLeft = BottomLeft;
            }
            // to ensure "BottomRight" is required (not null)
            if (BottomRight == null)
            {
                throw new InvalidDataException("BottomRight is a required property for Region and cannot be null");
            }
            else
            {
                this.BottomRight = BottomRight;
            }
            // to ensure "Center" is required (not null)
            if (Center == null)
            {
                throw new InvalidDataException("Center is a required property for Region and cannot be null");
            }
            else
            {
                this.Center = Center;
            }
            // to ensure "TopLeft" is required (not null)
            if (TopLeft == null)
            {
                throw new InvalidDataException("TopLeft is a required property for Region and cannot be null");
            }
            else
            {
                this.TopLeft = TopLeft;
            }
            // to ensure "TopRight" is required (not null)
            if (TopRight == null)
            {
                throw new InvalidDataException("TopRight is a required property for Region and cannot be null");
            }
            else
            {
                this.TopRight = TopRight;
            }
        }
        
        /// <summary>
        /// Gets or Sets BottomLeft
        /// </summary>
        [DataMember(Name="bottomLeft", EmitDefaultValue=false)]
        public Anchor BottomLeft { get; set; }
        /// <summary>
        /// Gets or Sets BottomRight
        /// </summary>
        [DataMember(Name="bottomRight", EmitDefaultValue=false)]
        public Anchor BottomRight { get; set; }
        /// <summary>
        /// Gets or Sets Center
        /// </summary>
        [DataMember(Name="center", EmitDefaultValue=false)]
        public Anchor Center { get; set; }
        /// <summary>
        /// Gets or Sets TopLeft
        /// </summary>
        [DataMember(Name="topLeft", EmitDefaultValue=false)]
        public Anchor TopLeft { get; set; }
        /// <summary>
        /// Gets or Sets TopRight
        /// </summary>
        [DataMember(Name="topRight", EmitDefaultValue=false)]
        public Anchor TopRight { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Region {\n");
            sb.Append("  BottomLeft: ").Append(BottomLeft).Append("\n");
            sb.Append("  BottomRight: ").Append(BottomRight).Append("\n");
            sb.Append("  Center: ").Append(Center).Append("\n");
            sb.Append("  TopLeft: ").Append(TopLeft).Append("\n");
            sb.Append("  TopRight: ").Append(TopRight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Region);
        }

        /// <summary>
        /// Returns true if Region instances are equal
        /// </summary>
        /// <param name="other">Instance of Region to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Region other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BottomLeft == other.BottomLeft ||
                    this.BottomLeft != null &&
                    this.BottomLeft.Equals(other.BottomLeft)
                ) && 
                (
                    this.BottomRight == other.BottomRight ||
                    this.BottomRight != null &&
                    this.BottomRight.Equals(other.BottomRight)
                ) && 
                (
                    this.Center == other.Center ||
                    this.Center != null &&
                    this.Center.Equals(other.Center)
                ) && 
                (
                    this.TopLeft == other.TopLeft ||
                    this.TopLeft != null &&
                    this.TopLeft.Equals(other.TopLeft)
                ) && 
                (
                    this.TopRight == other.TopRight ||
                    this.TopRight != null &&
                    this.TopRight.Equals(other.TopRight)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BottomLeft != null)
                    hash = hash * 59 + this.BottomLeft.GetHashCode();
                if (this.BottomRight != null)
                    hash = hash * 59 + this.BottomRight.GetHashCode();
                if (this.Center != null)
                    hash = hash * 59 + this.Center.GetHashCode();
                if (this.TopLeft != null)
                    hash = hash * 59 + this.TopLeft.GetHashCode();
                if (this.TopRight != null)
                    hash = hash * 59 + this.TopRight.GetHashCode();
                return hash;
            }
        }
    }

}
