/**
 * OCR
 * <b>The OCR API 'ocr' performs Optical Character Resolution on input files.</b>    The flow is generally as follows:  1. First upload an image/file using the /ocr POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /ocr/{jobid} endpoint, with the Job and Settings JSON as request body. The ocr extraction will now start.  3. Check the job status from the /ocr/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the OCR result using the /ocr/{jobid}/result GET endpoint. This will return the OCR result only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.ocr.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Region settings. For now you can specify 3 result mode for regions/coordinates in a lost. Simple, Relative regions and Absolute regions
 */
@ApiModel(description = "Region settings. For now you can specify 3 result mode for regions/coordinates in a lost. Simple, Relative regions and Absolute regions")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-10T16:52:55.758+02:00")
public class RegionSettings   {
  /**
   * Gets or Sets resultModes
   */
  public enum ResultModesEnum {
    @SerializedName("SIMPLE_INLINE")
    SIMPLE_INLINE("SIMPLE_INLINE"),
    
    @SerializedName("ABSOLUTE_POINTS")
    ABSOLUTE_POINTS("ABSOLUTE_POINTS"),
    
    @SerializedName("RELATIVE_POINTS")
    RELATIVE_POINTS("RELATIVE_POINTS");

    private String value;

    ResultModesEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("resultModes")
  private List<ResultModesEnum> resultModes = new ArrayList<ResultModesEnum>();

  public RegionSettings resultModes(List<ResultModesEnum> resultModes) {
    this.resultModes = resultModes;
    return this;
  }

  public RegionSettings addResultModesItem(ResultModesEnum resultModesItem) {
    this.resultModes.add(resultModesItem);
    return this;
  }

   /**
   * Get resultModes
   * @return resultModes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ResultModesEnum> getResultModes() {
    return resultModes;
  }

  public void setResultModes(List<ResultModesEnum> resultModes) {
    this.resultModes = resultModes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionSettings regionSettings = (RegionSettings) o;
    return Objects.equals(this.resultModes, regionSettings.resultModes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultModes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionSettings {\n");
    
    sb.append("    resultModes: ").append(toIndentedString(resultModes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

