/**
 * OCR
 * <b>The OCR API 'ocr' performs Optical Character Resolution on input files.</b>    The flow is generally as follows:  1. First upload an image/file using the /ocr POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /ocr/{jobid} endpoint, with the Job and Settings JSON as request body. The ocr extraction will now start.  3. Check the job status from the /ocr/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the OCR result using the /ocr/{jobid}/result GET endpoint. This will return the OCR result only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.ocr.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.sphereon.sdk.ocr.model.Region;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * word
 */
@ApiModel(description = "word")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-30T16:03:53.449+02:00")
public class Word   {
  @SerializedName("top")
  private Integer top = null;

  @SerializedName("left")
  private Integer left = null;

  @SerializedName("bottom")
  private Integer bottom = null;

  @SerializedName("right")
  private Integer right = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("region")
  private Region region = null;

  public Word top(Integer top) {
    this.top = top;
    return this;
  }

   /**
   * Simple location. See RegionSettings for more advanced location/region responses
   * @return top
  **/
  @ApiModelProperty(example = "null", value = "Simple location. See RegionSettings for more advanced location/region responses")
  public Integer getTop() {
    return top;
  }

  public void setTop(Integer top) {
    this.top = top;
  }

  public Word left(Integer left) {
    this.left = left;
    return this;
  }

   /**
   * Simple location. See RegionSettings for more advanced location/region responses
   * @return left
  **/
  @ApiModelProperty(example = "null", value = "Simple location. See RegionSettings for more advanced location/region responses")
  public Integer getLeft() {
    return left;
  }

  public void setLeft(Integer left) {
    this.left = left;
  }

  public Word bottom(Integer bottom) {
    this.bottom = bottom;
    return this;
  }

   /**
   * Simple location. See RegionSettings for more advanced location/region responses
   * @return bottom
  **/
  @ApiModelProperty(example = "null", value = "Simple location. See RegionSettings for more advanced location/region responses")
  public Integer getBottom() {
    return bottom;
  }

  public void setBottom(Integer bottom) {
    this.bottom = bottom;
  }

  public Word right(Integer right) {
    this.right = right;
    return this;
  }

   /**
   * Simple location. See RegionSettings for more advanced location/region responses
   * @return right
  **/
  @ApiModelProperty(example = "null", value = "Simple location. See RegionSettings for more advanced location/region responses")
  public Integer getRight() {
    return right;
  }

  public void setRight(Integer right) {
    this.right = right;
  }

  public Word text(String text) {
    this.text = text;
    return this;
  }

   /**
   * the text found by the OCR engine
   * @return text
  **/
  @ApiModelProperty(example = "null", required = true, value = "the text found by the OCR engine")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Word region(Region region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Region getRegion() {
    return region;
  }

  public void setRegion(Region region) {
    this.region = region;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Word word = (Word) o;
    return Objects.equals(this.top, word.top) &&
        Objects.equals(this.left, word.left) &&
        Objects.equals(this.bottom, word.bottom) &&
        Objects.equals(this.right, word.right) &&
        Objects.equals(this.text, word.text) &&
        Objects.equals(this.region, word.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(top, left, bottom, right, text, region);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Word {\n");
    
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    bottom: ").append(toIndentedString(bottom)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

