/* 
 * OCR
 *
 * <b>The OCR API 'ocr' performs Optical Character Resolution on input files.</b>    The flow is generally as follows:  1. First upload an image/file using the /ocr POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /ocr/{jobid} endpoint, with the Job and Settings JSON as request body. The ocr extraction will now start.  3. Check the job status from the /ocr/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the OCR result using the /ocr/{jobid}/result GET endpoint. This will return the OCR result only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Sphereon.SDK.Ocr.Client;
using Sphereon.SDK.Ocr.Model;

namespace Sphereon.SDK.Ocr.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOcrApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a job manually
        /// </summary>
        /// <remarks>
        /// Delete the OCR job and all related files
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRJobResponse</returns>
        OCRJobResponse DeleteJob (string jobid);

        /// <summary>
        /// Delete a job manually
        /// </summary>
        /// <remarks>
        /// Delete the OCR job and all related files
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        ApiResponse<OCRJobResponse> DeleteJobWithHttpInfo (string jobid);
        /// <summary>
        /// Job definition and state
        /// </summary>
        /// <remarks>
        /// Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRJobResponse</returns>
        OCRJobResponse GetJob (string jobid);

        /// <summary>
        /// Job definition and state
        /// </summary>
        /// <remarks>
        /// Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        ApiResponse<OCRJobResponse> GetJobWithHttpInfo (string jobid);
        /// <summary>
        /// Get all jobs
        /// </summary>
        /// <remarks>
        /// Get all OCR job definitions and their current state.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>OCRJobResponse</returns>
        OCRJobResponse GetJobs (List<string> status = null);

        /// <summary>
        /// Get all jobs
        /// </summary>
        /// <remarks>
        /// Get all OCR job definitions and their current state.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        ApiResponse<OCRJobResponse> GetJobsWithHttpInfo (List<string> status = null);
        /// <summary>
        /// Get the current ocr result
        /// </summary>
        /// <remarks>
        /// Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRResultResponse</returns>
        OCRResultResponse GetResult (string jobid);

        /// <summary>
        /// Get the current ocr result
        /// </summary>
        /// <remarks>
        /// Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRResultResponse</returns>
        ApiResponse<OCRResultResponse> GetResultWithHttpInfo (string jobid);
        /// <summary>
        /// Submit OCR job for processing
        /// </summary>
        /// <remarks>
        /// Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>OCRJobResponse</returns>
        OCRJobResponse SubmitJob (string jobid, OCRJob job);

        /// <summary>
        /// Submit OCR job for processing
        /// </summary>
        /// <remarks>
        /// Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        ApiResponse<OCRJobResponse> SubmitJobWithHttpInfo (string jobid, OCRJob job);
        /// <summary>
        /// Upload first file
        /// </summary>
        /// <remarks>
        /// Upload the first image file.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>OCRJobResponse</returns>
        OCRJobResponse UploadFile (System.IO.Stream stream);

        /// <summary>
        /// Upload first file
        /// </summary>
        /// <remarks>
        /// Upload the first image file.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        ApiResponse<OCRJobResponse> UploadFileWithHttpInfo (System.IO.Stream stream);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete a job manually
        /// </summary>
        /// <remarks>
        /// Delete the OCR job and all related files
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRJobResponse</returns>
        System.Threading.Tasks.Task<OCRJobResponse> DeleteJobAsync (string jobid);

        /// <summary>
        /// Delete a job manually
        /// </summary>
        /// <remarks>
        /// Delete the OCR job and all related files
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> DeleteJobAsyncWithHttpInfo (string jobid);
        /// <summary>
        /// Job definition and state
        /// </summary>
        /// <remarks>
        /// Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRJobResponse</returns>
        System.Threading.Tasks.Task<OCRJobResponse> GetJobAsync (string jobid);

        /// <summary>
        /// Job definition and state
        /// </summary>
        /// <remarks>
        /// Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> GetJobAsyncWithHttpInfo (string jobid);
        /// <summary>
        /// Get all jobs
        /// </summary>
        /// <remarks>
        /// Get all OCR job definitions and their current state.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>Task of OCRJobResponse</returns>
        System.Threading.Tasks.Task<OCRJobResponse> GetJobsAsync (List<string> status = null);

        /// <summary>
        /// Get all jobs
        /// </summary>
        /// <remarks>
        /// Get all OCR job definitions and their current state.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> GetJobsAsyncWithHttpInfo (List<string> status = null);
        /// <summary>
        /// Get the current ocr result
        /// </summary>
        /// <remarks>
        /// Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRResultResponse</returns>
        System.Threading.Tasks.Task<OCRResultResponse> GetResultAsync (string jobid);

        /// <summary>
        /// Get the current ocr result
        /// </summary>
        /// <remarks>
        /// Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRResultResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRResultResponse>> GetResultAsyncWithHttpInfo (string jobid);
        /// <summary>
        /// Submit OCR job for processing
        /// </summary>
        /// <remarks>
        /// Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>Task of OCRJobResponse</returns>
        System.Threading.Tasks.Task<OCRJobResponse> SubmitJobAsync (string jobid, OCRJob job);

        /// <summary>
        /// Submit OCR job for processing
        /// </summary>
        /// <remarks>
        /// Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> SubmitJobAsyncWithHttpInfo (string jobid, OCRJob job);
        /// <summary>
        /// Upload first file
        /// </summary>
        /// <remarks>
        /// Upload the first image file.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>Task of OCRJobResponse</returns>
        System.Threading.Tasks.Task<OCRJobResponse> UploadFileAsync (System.IO.Stream stream);

        /// <summary>
        /// Upload first file
        /// </summary>
        /// <remarks>
        /// Upload the first image file.
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> UploadFileAsyncWithHttpInfo (System.IO.Stream stream);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OcrApi : IOcrApi
    {
        private Sphereon.SDK.Ocr.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OcrApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OcrApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Sphereon.SDK.Ocr.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OcrApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OcrApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Sphereon.SDK.Ocr.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Sphereon.SDK.Ocr.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete a job manually Delete the OCR job and all related files
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRJobResponse</returns>
        public OCRJobResponse DeleteJob (string jobid)
        {
             ApiResponse<OCRJobResponse> localVarResponse = DeleteJobWithHttpInfo(jobid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a job manually Delete the OCR job and all related files
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        public ApiResponse< OCRJobResponse > DeleteJobWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->DeleteJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Delete a job manually Delete the OCR job and all related files
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRJobResponse</returns>
        public async System.Threading.Tasks.Task<OCRJobResponse> DeleteJobAsync (string jobid)
        {
             ApiResponse<OCRJobResponse> localVarResponse = await DeleteJobAsyncWithHttpInfo(jobid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete a job manually Delete the OCR job and all related files
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> DeleteJobAsyncWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->DeleteJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Job definition and state Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRJobResponse</returns>
        public OCRJobResponse GetJob (string jobid)
        {
             ApiResponse<OCRJobResponse> localVarResponse = GetJobWithHttpInfo(jobid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Job definition and state Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        public ApiResponse< OCRJobResponse > GetJobWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->GetJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Job definition and state Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRJobResponse</returns>
        public async System.Threading.Tasks.Task<OCRJobResponse> GetJobAsync (string jobid)
        {
             ApiResponse<OCRJobResponse> localVarResponse = await GetJobAsyncWithHttpInfo(jobid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Job definition and state Get the OCR job definition and current state. Please not that you can differentiate based on http response status
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> GetJobAsyncWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->GetJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Get all jobs Get all OCR job definitions and their current state.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>OCRJobResponse</returns>
        public OCRJobResponse GetJobs (List<string> status = null)
        {
             ApiResponse<OCRJobResponse> localVarResponse = GetJobsWithHttpInfo(status);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all jobs Get all OCR job definitions and their current state.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        public ApiResponse< OCRJobResponse > GetJobsWithHttpInfo (List<string> status = null)
        {

            var localVarPath = "/ocr/1.0.0/ocr";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (status != null) localVarQueryParams.Add("status", Configuration.ApiClient.ParameterToString(status)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJobs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Get all jobs Get all OCR job definitions and their current state.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>Task of OCRJobResponse</returns>
        public async System.Threading.Tasks.Task<OCRJobResponse> GetJobsAsync (List<string> status = null)
        {
             ApiResponse<OCRJobResponse> localVarResponse = await GetJobsAsyncWithHttpInfo(status);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all jobs Get all OCR job definitions and their current state.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">A list of status to filter on. (optional)</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> GetJobsAsyncWithHttpInfo (List<string> status = null)
        {

            var localVarPath = "/ocr/1.0.0/ocr";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (status != null) localVarQueryParams.Add("status", Configuration.ApiClient.ParameterToString(status)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJobs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Get the current ocr result Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>OCRResultResponse</returns>
        public OCRResultResponse GetResult (string jobid)
        {
             ApiResponse<OCRResultResponse> localVarResponse = GetResultWithHttpInfo(jobid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the current ocr result Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>ApiResponse of OCRResultResponse</returns>
        public ApiResponse< OCRResultResponse > GetResultWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->GetResult");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}/result";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetResult", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRResultResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRResultResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRResultResponse)));
            
        }

        /// <summary>
        /// Get the current ocr result Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of OCRResultResponse</returns>
        public async System.Threading.Tasks.Task<OCRResultResponse> GetResultAsync (string jobid)
        {
             ApiResponse<OCRResultResponse> localVarResponse = await GetResultAsyncWithHttpInfo(jobid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the current ocr result Get the OCR result  This API only returns the OCR when the response status code is 200! In other cases nothing is returned or the Job JSON when it is still being executed
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <returns>Task of ApiResponse (OCRResultResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRResultResponse>> GetResultAsyncWithHttpInfo (string jobid)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->GetResult");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}/result";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetResult", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRResultResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRResultResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRResultResponse)));
            
        }

        /// <summary>
        /// Submit OCR job for processing Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>OCRJobResponse</returns>
        public OCRJobResponse SubmitJob (string jobid, OCRJob job)
        {
             ApiResponse<OCRJobResponse> localVarResponse = SubmitJobWithHttpInfo(jobid, job);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Submit OCR job for processing Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        public ApiResponse< OCRJobResponse > SubmitJobWithHttpInfo (string jobid, OCRJob job)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->SubmitJob");
            // verify the required parameter 'job' is set
            if (job == null)
                throw new ApiException(400, "Missing required parameter 'job' when calling OcrApi->SubmitJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter
            if (job != null && job.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(job); // http body (model) parameter
            }
            else
            {
                localVarPostBody = job; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubmitJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Submit OCR job for processing Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>Task of OCRJobResponse</returns>
        public async System.Threading.Tasks.Task<OCRJobResponse> SubmitJobAsync (string jobid, OCRJob job)
        {
             ApiResponse<OCRJobResponse> localVarResponse = await SubmitJobAsyncWithHttpInfo(jobid, job);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Submit OCR job for processing Apply OCR on the previously uploaded file(s), using the supplied settings associated with the job in the request body. You can only submit the job after a new Job is created with status INPUTS_UPLOADED or resubmit an existing Job with status ERROR. In all cases the job Id in the path must match the jobId in the request
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobid">jobid</param>
        /// <param name="job">jobEntity</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> SubmitJobAsyncWithHttpInfo (string jobid, OCRJob job)
        {
            // verify the required parameter 'jobid' is set
            if (jobid == null)
                throw new ApiException(400, "Missing required parameter 'jobid' when calling OcrApi->SubmitJob");
            // verify the required parameter 'job' is set
            if (job == null)
                throw new ApiException(400, "Missing required parameter 'job' when calling OcrApi->SubmitJob");

            var localVarPath = "/ocr/1.0.0/ocr/{jobid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (jobid != null) localVarPathParams.Add("jobid", Configuration.ApiClient.ParameterToString(jobid)); // path parameter
            if (job != null && job.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(job); // http body (model) parameter
            }
            else
            {
                localVarPostBody = job; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubmitJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Upload first file Upload the first image file.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>OCRJobResponse</returns>
        public OCRJobResponse UploadFile (System.IO.Stream stream)
        {
             ApiResponse<OCRJobResponse> localVarResponse = UploadFileWithHttpInfo(stream);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Upload first file Upload the first image file.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>ApiResponse of OCRJobResponse</returns>
        public ApiResponse< OCRJobResponse > UploadFileWithHttpInfo (System.IO.Stream stream)
        {
            // verify the required parameter 'stream' is set
            if (stream == null)
                throw new ApiException(400, "Missing required parameter 'stream' when calling OcrApi->UploadFile");

            var localVarPath = "/ocr/1.0.0/ocr";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (stream != null) localVarFileParams.Add("stream", Configuration.ApiClient.ParameterToFile("stream", stream));

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

        /// <summary>
        /// Upload first file Upload the first image file.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>Task of OCRJobResponse</returns>
        public async System.Threading.Tasks.Task<OCRJobResponse> UploadFileAsync (System.IO.Stream stream)
        {
             ApiResponse<OCRJobResponse> localVarResponse = await UploadFileAsyncWithHttpInfo(stream);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Upload first file Upload the first image file.
        /// </summary>
        /// <exception cref="Sphereon.SDK.Ocr.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stream">The image file to convert to OCR</param>
        /// <returns>Task of ApiResponse (OCRJobResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OCRJobResponse>> UploadFileAsyncWithHttpInfo (System.IO.Stream stream)
        {
            // verify the required parameter 'stream' is set
            if (stream == null)
                throw new ApiException(400, "Missing required parameter 'stream' when calling OcrApi->UploadFile");

            var localVarPath = "/ocr/1.0.0/ocr";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (stream != null) localVarFileParams.Add("stream", Configuration.ApiClient.ParameterToFile("stream", stream));

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OCRJobResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OCRJobResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OCRJobResponse)));
            
        }

    }
}
